#
# configuration of the monitoring plugins
#
monitoring:
    monitor_time_interval: 5

    cpu_ram_usage:
        plots_time_span: 86400

    network_connections:
        min_connections: 5

    seed:
        desired_number_of_connections: 200
        maximum_number_of_connections: 400

    backbone:
        desired_number_of_connections: 200
        maximum_number_of_connections: 400

    prefer_backbone_exclusively:
        minimum_required_connections: 2

    free_disk_space:
        min_required_space: 5G

    feeds:
        steem_dollar_adjustment: 0.90
        enabled_assets: []   # [RUBLE, BTWTY, ALTCAP]
        disabled_assets: [RUB, SEK, GRIDCOIN, TCNY, CASH.BTC, KRW, TUSD, SGD, HKD]  # black swan
        asset_params:
            # FIXME: MCR and MSSR should be the actual percentage (float) not a fixed-point integer
            default:
                maintenance_collateral_ratio: 1750  # Call when collateral only pays off 175% the debt
                maximum_short_squeeze_ratio: 1100   # Stop calling when collateral only pays off 110% of the debt
                core_exchange_factor: 0.80          # 20% premium if paying fees in bitassets (avoids people draining the fee pool during price swings)
            TCNY:
                maintenance_collateral_ratio: 1750
                maximum_short_squeeze_ratio: 1001
            TUSD:
                maintenance_collateral_ratio: 1750
                maximum_short_squeeze_ratio: 1001
            CASH.USD:
                maintenance_collateral_ratio: 1750
                maximum_short_squeeze_ratio: 1001
            CASH.BTC:
                maintenance_collateral_ratio: 1750
                maximum_short_squeeze_ratio: 1001
            ALTCAP:
                maintenance_collateral_ratio: 1360
                maximum_short_squeeze_ratio: 1069
            RUBLE:
                maintenance_collateral_ratio: 1750
                maximum_short_squeeze_ratio: 1500
            HERO:
                maintenance_collateral_ratio: 2000
                maximum_short_squeeze_ratio: 1100

        check_time_interval: 300
        #publish_time_interval: 2400         # use this to publish feeds at fixed time intervals (in seconds)
        #publish_time_slot: 0                # use this to publish every hour at a fixed number of minutes (in minutes)
        median_time_span: 1800
        feed_providers: [Poloniex, Bittrex, Btc38, Yunbi,    # BTS valuation
                         Yahoo, Google, Bloomberg]  # market indices
        # List of feeds that should be shown on the UI and in the logs. Note that we
        # always check and publish all feeds, regardless of this variable.
        visible_feeds: [USD, BTC, CNY, GOLD, EUR]

    payroll:
        timezone_offset: 0                       # vps timezone difference from payee timezone (for logging purposes)
        pay_interval: 14                         # How often (in days) between each payday
        minimum_balance: 0                       # Amount to maintain in delegate account for fees
        payday_file: last_payday.dat             # Holds the date & time of the last payout
        transactions_file: transactions.txt      # Holds the list of payout transactions
        accounts: [account1, account2]           # List of accounts to pay for testing
        pay_rate: [60, 40]                       # Percentage to distribute to each account


