#
# list of clients that can be run
#
# by default, if you don't specify a client on the cmdline, the tools will
# run the client using the 'bts' run environment
#
run_environments:
    bts:
        type: bts

    bts2:
        type: bts2
        data_dir: ~/.BitShares2
        p2p_port: 1779
        witness_port: 8090
        cli_port: 8093

    seed:
        type: bts2
        data_dir: ~/.BitShares2_seed
        p2p_port: 1776
        witness_port: 8190
        cli_port: 8193

    backbone:
        type: bts2
        data_dir: ~/.BitShares2_backbone
        p2p_port: 1777
        witness_port: 8290
        cli_port: 8293

    muse:
        type: muse
        data_dir: ~/.Muse
        p2p_port: 1781
        witness_port: 8390
        cli_port: 8393

    steem:
        type: steem
        data_dir: ~/.Steem
        p2p_port: 2001
        witness_port: 8490
        cli_port: 8493

    debug:
        type: bts
        debug: true

    bts-dev:
        type: bts-dev

    dvs:
        type: dvs

    pts:
        type: pts

    pts-dev:
        type: pts-dev

    pls:
        type: pls
