---
# Config file containing the build, run and monitor environments and
# other configuration variables
#
# This file should contain sensible default values in as many places as
# possible, but you will have to at least specify your own values in the
# following categories:
#  - run_environments [for the cmdline tool]
#  - nodes            [for the monitoring webapp]
#
# For a more detailed description of the format of this file, visit:
# https://bts-tools.readthedocs.org/en/latest/config_format.html
#

# the logging levels for the different submodules
# can be any of DEBUG, INFO, WARNING, ERROR
logging:
    bts_tools: DEBUG
    bts_tools.core: INFO
    bts_tools.rpcutils: INFO
    bts_tools.monitoring: INFO
    bts_tools.notification: INFO
    bts_tools.feeds: INFO
    bts_tools.profile: INFO


# flags to be passed to make; shared among all build environments
make_args: ['-j2']

#
# list of configurations for building the bitshares client
#
# by default, if you don't specify a build env on the cmdline, the tools will
# use the 'bts' environment
#
build_environments:
    bts:
        git_repo: https://github.com/BitShares/bitshares.git
        git_branch: master
        build_dir: ~/.BitShares_build
        bin_dir: ~/.BitShares_bin
        bin_name: bitshares_client
        gui_bin_name: BitShares

    bts-dev:
        git_repo: https://github.com/BitShares/bitshares.git
        git_branch: develop
        build_dir: ~/.BitSharesDev_build
        bin_dir: ~/.BitSharesDev_bin
        bin_name: bitshares_client
        gui_bin_name: BitSharesTestNet

    dvs:
        git_repo: https://github.com/BitShares/bitshares.git
        git_branch: devshares
        build_dir: ~/.DevShares_build
        bin_dir: ~/.DevShares_bin
        bin_name: devshares_client
        gui_bin_name: DevShares

    pts:
        git_repo: https://github.com/PTS-DPOS/PTS.git
        git_branch: master
        build_dir: ~/.PTS_build
        bin_dir: ~/.PTS_bin
        bin_name: pts_client
        gui_bin_name: PTS

    pts-dev:
        git_repo: https://github.com/PTS-DPOS/PTS.git
        git_branch: develop
        build_dir: ~/.PTSdev_build
        bin_dir: ~/.PTSdev_bin
        bin_name: pts_client
        gui_bin_name: PTS

    sparkle:
        git_repo: https://github.com/sparkle5/Sparkle.git
        git_branch: sparkle
        build_dir: ~/.Sparkle_build
        bin_dir: ~/.Sparkle_bin
        bin_name: sparkle_client

    pls:
        git_repo: https://github.com/dacsunlimited/dac_play.git
        git_branch: master
        build_dir: ~/.Play_build
        bin_dir: ~/.Play_bin
        bin_name: play_client
        gui_bin_name: PLAY



# flags to be passed when running the client; shared among all run environments
# TODO: add '--accept-incoming-connections=0', but for delegate nodes only (ie: not for seed nodes)
#       see: https://bitsharestalk.org/index.php?topic=14150.msg184403#msg184403
run_args: ['--min-delegate-connection-count=0', '--statistics-enabled']

#
# list of clients that can be run
#
# by default, if you don't specify a client on the cmdline, the tools will
# run the client using the 'bts' run environment
#
run_environments:
    bts:
        type: bts

    debug:
        type: bts
        debug: true

    bts-dev:
        type: bts-dev

    dvs:
        type: dvs

    pts:
        type: pts

    pts-dev:
        type: pts-dev

    sparkle:
        type: sparkle

    pls:
        type: pls


# activate the debug flag on the wsgi app
wsgi_debug: false

# whether to profile how much time the RPC calls take to render
profile: false

#
# list of nodes (delegate accounts / seed nodes) that are being monitored
#
nodes:
    -
        client: bts
        type: seed
        name: seed-test
        monitoring: [seed]


#
# configuration of the monitoring plugins
#
monitoring:
    monitor_time_interval: 5

    cpu_ram_usage:
        plots_time_span: 86400

    network_connections:
        min_connections: 5

    seed:
        desired_number_of_connections: 200
        maximum_number_of_connections: 400

    feeds:
        check_time_interval: 300
        publish_time_interval: 2400
        median_time_span: 1800
        feed_providers: [Yahoo, Bter, Btc38, Poloniex]  # [Google, Bloomberg] also available
        visible_feeds: [USD, BTC, CNY, GOLD, EUR]

    payroll:
        timezone_offset: 0                       # vps timezone difference from payee timezone (for logging purposes)
        pay_interval: 14                         # How often (in days) between each payday
        minimum_balance: 0                       # Amount to maintain in delegate account for fees
        payday_file: last_payday.dat             # Holds the date & time of the last payout
        transactions_file: transactions.txt      # Holds the list of payout transactions
        accounts: [account1, account2]           # List of accounts to pay for testing
        pay_rate: [60, 40]                       # Percentage to distribute to each account


#
# configuration of the notification types
#
notification:
    email:
        smtp_server: smtp.example.com
        smtp_user: user
        smtp_password: secret-password
        identity: "BTS Monitor <bts_monitor@example.com>"
        recipient: me@example.com

    boxcar:
        tokens: []
